/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShamsButton {
        /**
          * A props / attribute that makes the button primary
         */
        "type": "primary" | "danger" | "primary-2";
    }
    interface ShamsIcons {
        /**
          * Name of the icon
         */
        "name": string;
    }
    interface ShamsTextInput {
        /**
          * Placeholder value
         */
        "errorMessage": string | null | undefined;
        /**
          * Label for the input
         */
        "label": string | null | undefined;
        /**
          * On change handler for input
         */
        "onInputChange": (event: Event) => void;
        /**
          * Placeholder value
         */
        "placeholder": string | null | undefined;
        /**
          * Value
         */
        "value": string | null | undefined;
    }
}
declare global {
    interface HTMLShamsButtonElement extends Components.ShamsButton, HTMLStencilElement {
    }
    var HTMLShamsButtonElement: {
        prototype: HTMLShamsButtonElement;
        new (): HTMLShamsButtonElement;
    };
    interface HTMLShamsIconsElement extends Components.ShamsIcons, HTMLStencilElement {
    }
    var HTMLShamsIconsElement: {
        prototype: HTMLShamsIconsElement;
        new (): HTMLShamsIconsElement;
    };
    interface HTMLShamsTextInputElement extends Components.ShamsTextInput, HTMLStencilElement {
    }
    var HTMLShamsTextInputElement: {
        prototype: HTMLShamsTextInputElement;
        new (): HTMLShamsTextInputElement;
    };
    interface HTMLElementTagNameMap {
        "shams-button": HTMLShamsButtonElement;
        "shams-icons": HTMLShamsIconsElement;
        "shams-text-input": HTMLShamsTextInputElement;
    }
}
declare namespace LocalJSX {
    interface ShamsButton {
        /**
          * A props / attribute that makes the button primary
         */
        "type"?: "primary" | "danger" | "primary-2";
    }
    interface ShamsIcons {
        /**
          * Name of the icon
         */
        "name"?: string;
    }
    interface ShamsTextInput {
        /**
          * Placeholder value
         */
        "errorMessage"?: string | null | undefined;
        /**
          * Label for the input
         */
        "label"?: string | null | undefined;
        /**
          * On change handler for input
         */
        "onInputChange"?: (event: Event) => void;
        /**
          * Placeholder value
         */
        "placeholder"?: string | null | undefined;
        /**
          * Value
         */
        "value"?: string | null | undefined;
    }
    interface IntrinsicElements {
        "shams-button": ShamsButton;
        "shams-icons": ShamsIcons;
        "shams-text-input": ShamsTextInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shams-button": LocalJSX.ShamsButton & JSXBase.HTMLAttributes<HTMLShamsButtonElement>;
            "shams-icons": LocalJSX.ShamsIcons & JSXBase.HTMLAttributes<HTMLShamsIconsElement>;
            "shams-text-input": LocalJSX.ShamsTextInput & JSXBase.HTMLAttributes<HTMLShamsTextInputElement>;
        }
    }
}
